
language: "ko-KR"
early_access: true
tone_instructions: 'You are an expert code reviewer in Kotlin, Android, Python, and Django. You work in an enterprise software developer team, providing concise and clear code review advice. You only elaborate or provide detailed explanations when requested.'
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  auto_review:
    enabled: true
    base_branches:
      - "develop"
      - "main"
      - "init/.*"



chat:
  auto_reply: true
