# Generated by Django 5.2.7 on 2025-10-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptoption",
            name="key",
            field=models.CharField(
                choices=[("tone", "tone"), ("format", "format"), ("other", "other")], max_length=30
            ),
        ),
    ]
