# Generated by Django 5.2.7 on 2025-10-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_promptoption_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="options",
            field=models.ManyToManyField(related_name="groups", to="contact.promptoption"),
        ),
        migrations.DeleteModel(
            name="GroupOptionMap",
        ),
    ]
