# Generated by Django 5.2.7 on 2025-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_group_options_delete_groupoptionmap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactcontext",
            old_name="relationship_role",
            new_name="recipient_role",
        ),
        migrations.AddField(
            model_name="contactcontext",
            name="sender_role",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
