# Generated by Django 5.2.7 on 2025-10-25 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_rename_relationship_role_contactcontext_recipient_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contacts", to="contact.group"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="contactcontext",
            name="language_preference",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
