# Generated by Django 5.2.8 on 2025-11-12 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contact_group_alter_contact_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="background_color",
            field=models.CharField(
                default="#FFFFFF",
                help_text="앱에서 표시할 배경색 (#RRGGBB 형식)",
                max_length=7,
                validators=[django.core.validators.RegexValidator(message="색상은 #RRGGBB 형태의 16진수여야 합니다.", regex="^#([0-9A-Fa-f]{6})$")],
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="emoji",
            field=models.CharField(blank=True, help_text="그룹 이모지 (예: 🔥, 💬, 👩🏽\u200d❤️\u200d👨🏿 등)", max_length=16),
        ),
    ]
