# Generated by Django 5.2.7 on 2025-11-09 08:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact", "0005_alter_contact_group_alter_contact_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactAnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("last_analysis_id", models.IntegerField(blank=True, null=True)),
                ("lexical_style", models.TextField()),
                ("grammar_patterns", models.TextField()),
                ("emotional_tone", models.TextField()),
                ("figurative_usage", models.TextField()),
                ("long_sentence_ratio", models.TextField()),
                ("representative_sentences", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                (
                    "contact",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contact_anaylsis_result", to="contact.contact"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contact_anaylsis_result", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupAnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("last_analysis_id", models.IntegerField(blank=True, null=True)),
                ("lexical_style", models.TextField()),
                ("grammar_patterns", models.TextField()),
                ("emotional_tone", models.TextField()),
                ("figurative_usage", models.TextField()),
                ("long_sentence_ratio", models.TextField()),
                ("representative_sentences", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_analysis_result", to="contact.group")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_anaylsis_result", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MailAnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("lexical_style", models.TextField()),
                ("grammar_patterns", models.TextField()),
                ("emotional_tone", models.TextField()),
                ("figurative_usage", models.TextField()),
                ("long_sentence_ratio", models.TextField()),
                ("representative_sentences", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                (
                    "contact",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mail_anaylsis_result", to="contact.contact"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mail_anaylsis_result", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
