# Generated by Django 5.2.8 on 2025-11-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactanalysisresult",
            name="figurative_usage",
        ),
        migrations.RemoveField(
            model_name="contactanalysisresult",
            name="long_sentence_ratio",
        ),
        migrations.RemoveField(
            model_name="groupanalysisresult",
            name="figurative_usage",
        ),
        migrations.RemoveField(
            model_name="groupanalysisresult",
            name="long_sentence_ratio",
        ),
        migrations.RemoveField(
            model_name="mailanalysisresult",
            name="figurative_usage",
        ),
        migrations.RemoveField(
            model_name="mailanalysisresult",
            name="long_sentence_ratio",
        ),
        migrations.AlterField(
            model_name="contactanalysisresult",
            name="emotional_tone",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="contactanalysisresult",
            name="grammar_patterns",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="contactanalysisresult",
            name="lexical_style",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="groupanalysisresult",
            name="emotional_tone",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="groupanalysisresult",
            name="grammar_patterns",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="groupanalysisresult",
            name="lexical_style",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="mailanalysisresult",
            name="emotional_tone",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="mailanalysisresult",
            name="grammar_patterns",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="mailanalysisresult",
            name="lexical_style",
            field=models.JSONField(),
        ),
    ]
