from pydantic import BaseModel, Field


class ReplyOption(BaseModel):
    type: str = Field(
        ...,
        description=(
            "A free-form label describing the reply type, generated by the LLM "
            "(e.g., Positive response, Scheduling adjustment, Polite apology, etc.)."
        ),
    )
    title: str = Field(..., description="Short one-line title in target language (no quotes, no trailing punctuation)")


class ReplyPlan(BaseModel):
    language: str
    options: list[ReplyOption] = Field(..., min_length=2, max_length=4)


class ValidationResult(BaseModel):
    passed: bool = Field(..., description="True if the body passes validation")
    rewrite_instructions: str = Field("", description="Short instructions to fix issues if validation failed")
