from pydantic import BaseModel, Field


class ReplyOption(BaseModel):
    type: str = Field(
        ...,
        description=(
            "A free-form label describing the reply type, generated by the LLM "
            "(e.g., Positive response, Scheduling adjustment, Polite apology, etc.)."
        ),
    )
    title: str = Field(..., description="Short one-line title in target language (no quotes, no trailing punctuation)")


class ReplyPlan(BaseModel):
    language: str
    options: list[ReplyOption] = Field(..., min_length=2, max_length=4)


class ValidationResult(BaseModel):
    passed: bool = Field(..., description="True if the body passes validation")
    rewrite_instructions: str = Field("", description="Short instructions to fix issues if validation failed")


class SpeechAnalysis(BaseModel):
    lexical_style: str
    grammar_patterns: str
    emotional_tone: str
    figurative_usage: str
    long_sentence_ratio: str
    representative_sentences: list[str] = Field(default_factory=list)


class AttachmentAnalysisResult(BaseModel):
    summary: str = Field(..., description="High-level summary of the attachment. Write 3–10 sentences depending on file length.")
    insights: str = Field(..., description="Key insights or action points extracted from the document.")
    mail_guide: str = Field(
        ..., description="Guidance on how to reference this attachment in an email — what to include in subject, introduction, and key body points."
    )
