# Generated by Django 5.2.6 on 2025-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_unread",
            field=models.BooleanField(default=True),
        ),
    ]
