# Generated by Django 5.2.7 on 2025-10-15 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
        ("mail", "0002_email_is_unread"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("provider", models.CharField(db_index=True, default="gmail", max_length=20)),
                ("external_message_id", models.CharField(blank=True, max_length=255)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField()),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(db_index=True)),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_mails",
                        to="contact.contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at", "-id"],
            },
        ),
        migrations.DeleteModel(
            name="Email",
        ),
        migrations.AddIndex(
            model_name="sentmail",
            index=models.Index(fields=["user", "sent_at"], name="mail_sentma_user_id_41f959_idx"),
        ),
        migrations.AddIndex(
            model_name="sentmail",
            index=models.Index(fields=["provider", "thread_id"], name="mail_sentma_provide_0c3955_idx"),
        ),
        migrations.AddConstraint(
            model_name="sentmail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_message_id", ""), _negated=True),
                fields=("provider", "external_message_id"),
                name="uniq_sentmail_provider_external_message_id_nonblank",
            ),
        ),
    ]
