# Generated by Django 5.2.8 on 2025-11-08 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_sentmail_delete_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.CharField(blank=True, default="", max_length=255)),
                ("attachment_id", models.CharField(blank=True, default="", max_length=800)),
                ("content_key", models.CharField(blank=True, default="", max_length=255)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("summary", models.TextField(blank=True, default="")),
                ("insights", models.TextField(blank=True, default="")),
                ("mail_guide", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "attachment_id"], name="mail_attach_user_id_98ae73_idx"),
                    models.Index(fields=["user", "content_key"], name="mail_attach_user_id_53fa21_idx"),
                ],
            },
        ),
    ]
