# Generated by Django 5.2.6 on 2025-10-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_refresh_token_googleaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleaccount",
            name="access_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="googleaccount",
            name="refresh_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="googleaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_accounts",
                to="user.user",
                unique=True,
            ),
        ),
    ]
