# Generated by Django 5.2.8 on 2025-11-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(blank=True, help_text="사용자가 선호하는 언어", max_length=30),
        ),
    ]
